### ISSUE TITLE
index.ts 이해가 안되는 코드가 있습니다.

### ISSUE THREAD

**Issue by HyeanWoo** [yg1110/Zoom#1]
```ts
import {testMakePerson} from "./Types/makePerson";

require("./style/style.scss");
require("./style/style.css");

testMakePerson();
```
부분에서 `import`문과 `require`문을 섞어서 사용중이신데, 이렇게 한 이유가 있나요?
빠른 답변 부탁드립니다.

**Comment by yg1110** [comment]
별다른 이유는 없습니다.
서로 다른 날짜에 코딩해서,
그날 그날 기분에 따라 무지성으로 코드 쳐서 그렇습니다.

**Comment by HyeanWoo** [comment]
그리고 조금 더 열심히 해보시길 바랍니다. 저는 타입스크립트를 몰라서 여기 레포를 보고 공부할까 생각중이라😉

**Comment by yg1110** [comment]
조언감사합니다.
시간이 된다면 조금씩 올리겠습니다.😉
